//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace findmyzone.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("findmyzone.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier déjà présent ({0}).
        /// </summary>
        internal static string AlreadyDownloaded {
            get {
                return ResourceManager.GetString("AlreadyDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code INSEE devrait avoir 5 chiffres (au lieu de {0} pour {1}).
        /// </summary>
        internal static string CodeShouldHave5Digits {
            get {
                return ResourceManager.GetString("CodeShouldHave5Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisation du dossier de téléchargement: {0}.
        /// </summary>
        internal static string DownloadDir {
            get {
                return ResourceManager.GetString("DownloadDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun code INSEE n&apos;a pu être trouvé....
        /// </summary>
        internal static string NoInseeCodes {
            get {
                return ResourceManager.GetString("NoInseeCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Décompression du fichier {0}.
        /// </summary>
        internal static string UngzipFile {
            get {
                return ResourceManager.GetString("UngzipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ville &quot;{0}&quot; n&apos;a pas été trouvée.
        /// </summary>
        internal static string WrongCityName {
            get {
                return ResourceManager.GetString("WrongCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code postal &quot;{0}&quot; n&apos;a pas été trouvé.
        /// </summary>
        internal static string WrongZipCode {
            get {
                return ResourceManager.GetString("WrongZipCode", resourceCulture);
            }
        }
    }
}
